# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
addons:
  chrome: stable # https://docs.travis-ci.com/user/chrome

dist: trusty # Chrome driver fails if not trusty dist

# Chrome Webdriver fails if not on sudo
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: true

notifications:
  email: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - mysql
  - postgresql
  - redis
  - rabbitmq

addons:
  postgresql: "9.6"

env:
  - ES_VERSION=6.2.2 E2E="no"
  - ES_VERSION=6.2.2 E2E="yes" E2E_OUTPUT="base64"

python:
  - "2.7"
  - "3.5"

before_install:
  # Download and start ES
  - mkdir /tmp/elasticsearch
  - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - "/tmp/elasticsearch/bin/elasticsearch &"
  # Chrome webdriver for Selenium
  - "PATH=$PATH:$HOME/webdrivers"
  - "if [ ${E2E} == 'yes' ] && [ ! -f $HOME/webdrivers/chromedriver ]; then wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -P $HOME/webdrivers; unzip -d $HOME/webdrivers $HOME/webdrivers/chromedriver_linux64.zip; fi"
  - "nvm install 6; nvm use 6"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install cookiecutter"
  - "travis_retry pip install Sphinx>=1.4.2"

before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "if [ ${E2E} == 'yes' ]; then sh -e /etc/init.d/xvfb start; sleep 3; fi"

script:
  - "./run-tests.sh"

after_success:
  - coveralls
